### ISSUE TITLE
No Matching Handler reports Handler Error with No Spaces

### ISSUE THREAD

**Issue by knabity** [mockery/mockery#597] opened 2016-05-13 16:25 UTC
I'm not sure if this is just an issue with mockery or both PHPUnit and Mockery.  

Let's say I write a mock for a method that contains the parameter "John Doe".  The actual code being tested looks something like:

`mock->someMethod('John Doe');`

I assert that mock using the incorrect with() value 'wrongValue':

```
$this->mock
        ->shouldReceive('someMethod')
        ->with('wrongValue')
        ->andReturn();
```

I run the test and I get the error:

`No Matching handler found for Mockery_11_App_Repositories_MockRepositoryInterface::someMethod('JohnDoe').  Either the method was unexpected or its arguments matched no expected argument list for this method.   
`

The error should include a space between John and Doe and look like:

`No Matching handler found for Mockery_11_App_Repositories_MockRepositoryInterface::someMethod('John Doe').  Either the method was unexpected or its arguments matched no expected argument list for this method.`

This really does become a problem at times with larger values passed in.  Especially when it's telling you the wrong values that should go in the methods and throwing an error when you put in what Mockery requests.

**Comment by nobuf** [comment] 2016-05-30 21:32
I've tried adding a method below in MockTest.php (with phpunit 4.8.21), but no luck to reproduce :(

```
public function testMockWithWrongArgument()
{
    $m = Mockery::mock('ClassWithMethods');
    $m->shouldReceive('foo')
        ->with('Jack Doe')
        ->andReturnNull();
    $m->foo('John Doe');
}
```

```
No matching handler found for Mockery_0_ClassWithMethods::foo('John Doe'). Either the method was unexpected or its arguments matched no expected argument list for this method
```

`Mockery::formatArgument()` formats the argument but it doesn't look like it strips any space:

```php
return "'".(string) $argument."'";
```

**Comment by knabity** [comment] 2016-05-31 12:58
Weird.  I'm using PHPUnit 4.8.26, but I don't think the version is the issue, since I have had this problem for almost a year now in different environments.  My manager is having the same problem.  We are using PHPUnit on top of CentOS.  I am running the tests via the command line.  I have also run them from PHPStorm in Windows and in Linux Mint.  Mockery is version 0.9.5 I don't know if it makes a difference, but it looks like you called the method in the same file as the test.  The way I have it set up, the actual method call is in a separate file in the controller.

**Comment by robertbasic** [comment] 2017-05-09 11:57
I know I have seen this issue before, but I can't reproduce it now, nor do I see anything in the code that would make it behave this way. It might have been "accidentally" fixed in the meantime.

I have tried with Mockery only, and as a part of PHPUnit (granted, with PHPUnit 6).

I'm going to close this issue now, but if this is something you still have problems with, please reopen it. If you provide a small, reproducible test case, that would be greatly appreciated.

Thanks!

**Closed by robertbasic** 2017-05-09 11:57 UTC
Labels: bug, investigate
