### ISSUE TITLE
Upgrade vom 1.1.0 to 1.3.0 gives memory leaks

### ISSUE THREAD

**Issue by pscheit** [mockery/mockery#1026] opened 2019-11-28 15:51 UTC
Hi there,

thanks for writing mockery! I use it for ages now, and still happy.

I upgraded my Symfony Application and the mockery lib as well. Now I get memory errors, when mockery tries to boot its container:

```
Fatal error: Allowed memory size of 4294967296 bytes exhausted (tried to allocate 262144 bytes) in /app/vendor/mockery/mockery/library/Mockery.php on line 230
```
This happens in teardown after just one test.

any idea where to start look at?

Its Integrated with PHPUnit 8x via trait

**Comment by davedevelopment** [comment] 2019-11-28 16:00
Could be related to #1023

**Comment by robertbasic** [comment] 2019-12-04 04:29
Hey @pscheit !

Could you please provide us the versions of PHP, PHPUnit, and Mockery that you are using? Thanks!

**Comment by pscheit** [comment] 2019-12-04 08:01
sure!
PHP 7.2.20 (cli) (built: Jul 12 2019 23:48:07) ( NTS )
mockery: 1.3.0
phpunit 8.3.5 (composer install)

**Comment by pscheit** [comment] 2019-12-04 08:39
I upgraded php to PHP 7.3.7 (cli) (built: Jul 12 2019 22:53:38) ( NTS )
but that has the same result

**Comment by LeSuisse** [comment] 2019-12-17 22:05
Hi,

I observe a similar issue since the bump for no obvious reason. I have been able to reproduce the issue consistently with our test suite. It's a bit weird though because the same test class is perfectly fine when executed on its own and runs fine with Mockery 1.2.3.

After a git bisect it seems the issue is here since 8b3789415c1a86f5623af5a48615592246163589.

**Comment by pscheit** [comment] 2019-12-18 07:16
ooh ! That's a good hint. Maybe it does try to serialize/printf some really big objects recursively?

**Comment by LeSuisse** [comment] 2019-12-18 09:41
After taking a closer look to the code, it seems that building NoMatchingExpectationException can take a while and consume a not negligible amount of memory especially when the arguments are no so small objects (e.g. mocks).
It is probably fine when the exception is used immediately but when the assertions not verified immediately (like when using Mockery::spy()) it can be a resource waste because the exception might never be thrown.

https://github.com/mockery/mockery/blob/c21660612104ad072bbc3f0f3d934689160924dc/library/Mockery/Mock.php#L880-L882

**Comment by robertbasic** [comment] 2019-12-26 09:52
@pscheit @LeSuisse I just released 1.3.1 where I reverted the changes from #1000, could you please retest and see if the memory leak still happens? Thank you!

**Comment by LeSuisse** [comment] 2019-12-26 11:07
I confirm that I'm no more able to reproduce the issue with 1.3.1.


It's a bit sad, that was a nice feature :disappointed: but I'm not sure how we can generate the exception message in a lazy way with PHP < 7 and anyway there is still the BC.

**Comment by robertbasic** [comment] 2019-12-26 11:09
Thanks for the confirmation, I'll close this issue now if you don't mind :)

**Closed by robertbasic** 2019-12-26 11:09 UTC
Labels: investigate

**Comment by pscheit** [comment] 2020-02-20 04:29
unfortunately i still have those memory leaks (same as above). It's in a not failing unit test.

Downgrading to 1.1.0 helps

**Comment by pscheit** [comment] 2020-03-11 20:42
oh lord! 

My bad, I constructed a nice recursion, which had absolutely nothing to do with mockery
