### ISSUE TITLE
Unable to mock object when constructor calls public method

### ISSUE THREAD

**Issue by kgkg** [mockery/mockery#803] opened 2017-10-25 08:36 UTC
Given I have a class which calls public method in constructor:

````
class MockeryExample
{
    public function __construct($arg)
    {
        $this->foo();
    }

    public function foo()
    {
    }
}
````

When I try to create a mock for that class:
`$mock = \Mockery::mock(MockeryExample::class, [1]);`

Then I get 

> Received Mockery_0_MockeryExample::foo(), but no expectations were specified
 C:\usr\htdocs\game\classes\MockeryExample.php:12
 C:\usr\htdocs\game\vendor\mockery\mockery\library\Mockery\Container.php:478
 C:\usr\htdocs\game\vendor\mockery\mockery\library\Mockery\Container.php:225
 C:\usr\htdocs\game\vendor\mockery\mockery\library\Mockery.php:82
 C:\usr\htdocs\game\tests\unit\MockeryExampleTest.php:17

The same happens when I use
`$mock = \Mockery::spy(MockeryExample::class, [1]);`
or
`$mock = \Mockery::mock(MockeryExample::class, [1])->shouldIgnoreMissing();`

It works fine when:
- I change foo() into protected or private
- **OR** when I remove contructor argument from mock function:
`$mock = \Mockery::mock(MockeryExample::class);`

I'm using latest dev-master.

**Comment by robertbasic** [comment] 2018-02-05 13:17
Thanks for the report @kgkg, but if you don't mind I'm closing this issue as it is a duplicate of #534. Just trying to bring some order to the issue tracker :)

**Closed by robertbasic** 2018-02-05 13:17 UTC
