### ISSUE TITLE
Default expectations override logic ignores the ->with() part of the expectation

### ISSUE THREAD

**Issue by a-barzanti** [mockery/mockery#783] opened 2017-08-30 13:04 UTC
The override mechanism of the default expectations overrides only the expectations that have been redefined. 
```
        $myMock = \Mockery::mock();
        $myMock->shouldReceive('qux')->andReturn('default-qux')->byDefault();
        $myMock->shouldReceive('baz')->andReturn('default-baz')->byDefault();
        $myMock->shouldReceive('qux')->andReturn('qux');
        self::assertSame('qux', $myMock->qux());
        self::assertSame('default-baz', $myMock->baz());
```
But when overriding default expectations that differs only in the ->with() part, the override applies to all the default expectations (disabling the expectations that have not been redefined):
```
        $myMock = \Mockery::mock();
        $myMock->shouldReceive('foobar')->with('foo')->andReturn('default-foo')->byDefault();
        $myMock->shouldReceive('foobar')->with('bar')->andReturn('default-bar')->byDefault();
        $myMock->shouldReceive('foobar')->with('foo')->andReturn('foo');
        self::assertSame('foo', $myMock->foobar('foo'));
        self::assertSame('default-bar', $myMock->foobar('bar'));
        // Throws: No matching handler found for Mockery_0::foobar("bar"). Either the method was unexpected or its arguments matched no expected argument list for this method
```

**Comment by davedevelopment** [comment] 2017-09-05 10:35
I don't know if this is by design or not, my gut feeling is that it is...

**Comment by robertbasic** [comment] 2018-02-04 07:58
@a-barzanti what version of Mockery are you using? I can't reproduce this:

``` php
$myMock = \Mockery::mock();
$myMock->shouldReceive('foobar')->with('foo')->andReturn('default-foo')->byDefault();
$myMock->shouldReceive('foobar')->with('bar')->andReturn('default-bar')->byDefault();
$myMock->shouldReceive('foobar')->with('foo')->andReturn('foo');

var_dump($myMock->foobar('foo'));
var_dump($myMock->foobar('bar'));
```

``` bash
robert@odin ~/projects/mockery[master*]$ php adhoc-tests/issue783.php 
/home/robert/projects/mockery/adhoc-tests/issue783.php:12:
string(3) "foo"
/home/robert/projects/mockery/adhoc-tests/issue783.php:13:
string(11) "default-bar"
```

Thanks!

**Comment by a-barzanti** [comment] 2018-02-05 09:06
@robertbasic it was 0.9.4, I cannot reproduce on 1.0.

**Comment by robertbasic** [comment] 2018-02-05 09:07
@a-barzanti thanks, that means this was fixed in the meantime. Are you OK with closing this issue?

**Comment by a-barzanti** [comment] 2018-02-05 09:09
@robertbasic Yes, thank you for investigating, and letting me know it's no longer an issue. I can simplify my tests now.

**Comment by robertbasic** [comment] 2018-02-05 09:09
Thank you!

**Closed by robertbasic** 2018-02-05 09:09 UTC
