### ISSUE TITLE
Issue when mocking methods implemented in `__call`

### ISSUE THREAD

**Issue by RSully** [mockery/mockery#204] opened 2013-09-17 19:13 UTC
I am attempting to mock a class that I wrote as a simple wrapper around curl. Rather than implement all of the functions I simply implemented `__call` to pass calls to the `curl_` functions. 

The issue with Mockery presents itself when I use it as follows:

``` php
$curl = \Mockery::mock('Project\Support\Curl[exec]')->makePartial();
$curl->shouldReceive('exec')->once()->andReturn(false);
```

(I tried with & without `[exec]`. If I omit `makePartial()` then it tells me `Method Project\Support\Curl::setoptArray() does not exist on this mock object`)

Error message:

```
Fatal error: Maximum function nesting level of '100' reached, aborting! in /project/vendor/mockery/mockery/library/Mockery/Generator.php(129) : eval()'d code on line 126
```

For now I can get around this by using PHPUnit Mocks:

``` php
$curl = $this->getMock('Project\Support\Curl', ['exec']);
$curl->expects($this->once())->method('exec')->will($this->returnValue(false));
```

---

Class:

``` php

<?php namespace Project\Support;

use Illuminate\Support\Str;

class Curl {

    /**
     * @var resource
     */
    protected $ch;

    /**
     * @param null|string $url
     */
    public function __construct($url = null)
    {
        $this->ch = curl_init($url);
    }

    /**
     * @param string $name
     * @param array $args
     * @return mixed
     * @throws \BadFunctionCallException
     */
    public function __call($name, $args)
    {
        $function = 'curl_' . Str::snake($name);

        if (! function_exists($function))
        {
            throw new \BadFunctionCallException("Function not found");
        }

        array_unshift($args, $this->ch);
        return call_user_func_array($function, $args);
    }
}
```

**Comment by pawlik** [comment] 2015-04-24 02:08
I experienced the same. Tried to us proxied partial mocks, it fixes the issue (max nesting level), but then when I try to set some expectations on this mock - original method (not virtual) is called anyway.

**Comment by robertbasic** [comment] 2017-05-09 05:47
Due to the age of this issue, it might have been fixed in the meantime, as I can't reproduce it with the example provided.

Please use the latest master, or the 1.0.0-alpha tag, to check is this still an issue for you, or not. If it is, please reopen this issue and provide a small, reproducible test case.

Thank you!

**Closed by robertbasic** 2017-05-09 05:47 UTC
Labels: blocker, bug

**Comment by flyingL123** [comment] 2018-03-04 04:10
I could be wrong but I think this is still an issue. I'm using Mockery ~1.0. I am creating a wrapper around a class that uses static methods, and trying to test that a method call is properly forwarded to that static class.

Here's the relevant part of the class under test:

```
class Bigcommerce
{
    public function __call($name, $args)
    {
        return call_user_func_array(Api\Bigcommerce\Client::class . '::' . $name, $args);
    }
}
```

And the test:

```
/**
 * @test
 */
public function it_should_pass_an_undefined_method_call_through_to_the_client()
{
	$bigcommerce = Mockery::mock(Bigcommerce::class, ['client_id', 'client_secret', 'redirect_uri'])->makePartial();
        $clientMock = Mockery::mock('alias:Bigcommerce\Api\Client');

	$clientMock
		->expects()
		->someMethod('foo', 'bar');

	$this->bigcommerce->someMethod('foo', 'bar');
}
```
Running this results in an error:

> Mockery\Exception\BadMethodCallException: Method Mockery_0_App_Bigcommerce::someMethod() does not exist on this mock object

So I tried adding an expectation for `someMethod`, and setting it to `passthru`:

```
$bigcommerce
	    ->expects()
	    ->someMethod('foo', 'bar')
	    ->passthru();
```

Which results in this error:

> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /Users/me/project/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code on line 372
> 
> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /Users/me/project/vendor/composer/ClassLoader.php on line 321

Shouldn't the `passthru` tell the partial mock to pass the call to the original class, which would hit the classes `__call` method and send it to the client mock?

**Comment by davedevelopment** [comment] 2018-03-05 09:15
@flyingL123 unfortunately we don't handle that kind of situation. Mockery relies on `__call` to implement most of it's functionality and from there it's quite a mess of trying to work out whether we should act on the call, or pass it on to the parent. In your example, does `$bigcommerce` have to be a mock? Could you use a concrete object?
