### ISSUE TITLE
A never-returning function must not return

### ISSUE THREAD

**Issue by michaelw85** [mockery/mockery#1240] opened 2023-04-19 15:49 UTC
Hi,

I'm running into some issues with the `never` type when mocking WordPress functions using Brain Monkey.
Specifically when using the `when` and `expect` functions from Brain Monkey.

The error: `A never-returning function must not return`.

I'm using PHP **8.1** with:

> phpunit/phpunit **10.1.0**
> brain/monkey **2.6.1**
> pestphp/pest **v2.5.0**
> mockery/mockery **1.5.1**

I've created an issue in the pest and brain/monkey repo but this issue might be in the mockery code.
I haven't been able to really find the source yet. I did find a workaround by patching all `never` types to `void` in Pest and PHPUnit.

Related tickets:

- https://github.com/pestphp/pest/pull/786
- https://github.com/Brain-WP/BrainMonkey/issues/135
- https://github.com/pestphp/pest/issues/785

**Comment by ghostwriter** [comment] 2023-04-19 16:33
Hey @michaelw85,

Thanks for reporting this issue.

We added support for `never` type for PHP 8.1  via https://github.com/mockery/mockery/pull/1184 and tagged [1.5.1](https://github.com/mockery/mockery/commits/1.5.1)

However, It looks like `Brain-WP/BrainMonkey` is using an older version of mockery ([`^1.3.5 || ^1.4.4`](https://github.com/Brain-WP/BrainMonkey/blob/2.6.1/composer.json#L31)).

Hope that is helpful.

**Comment by ghostwriter** [comment] 2023-04-19 17:04
If you can, please provide a small test case to reproduce the issue and I'll take a closer look.

**Comment by michaelw85** [comment] 2023-04-19 18:55
@ghostwriter I spent some time debugging and have a better understanding of when the issue occurs.
Here's a repo https://github.com/michaelw85/never-issue#readme

I'm not sure if this actually is an issue with Mockery, I'm starting to think this might be caused by Pest.

**Comment by ghostwriter** [comment] 2023-04-19 20:22
@michaelw85  Thank you.

I was able to reproduce the issue.

I agree, **the root cause seems to be `Pest`**.

It's possible that `Pest` automatically calls facades and proxy methods internally, similar to Laravel. 

This could be causing the call to `Expectation::toBeUsed()` or `HigherOrderExpectation::toBeUsed()` to return.

---

P.S. Moving the `expect(true)->toBeTrue();` in `ExampleTest.php` to the top also gets this `running` and `passing` again. 

```diff
test('example', function () {
+    expect(true)->toBeTrue();
    // When commenting both methods to mock a function the test runs fine.
    when('update_option')->justReturn('foo');
    expectFunction('get_option')->once()->andReturn('foo');
    
+    expect(get_option())->toEqual('foo');
-    expect(true)->toBeTrue();
});
```

---

I'm going to close this since we've re-confirmed that the issue is not with Mockery.

**Closed by ghostwriter** 2023-04-19 20:23 UTC

**Comment by michaelw85** [comment] 2023-04-20 05:34
@ghostwriter Thank you for taking the time and helping out. I'm going to try and see if I can find the root cause now that I have a better lead where to look.
