### ISSUE TITLE
When mocking public static methods, number of calls to a method is increased incorrectly

### ISSUE THREAD

**Issue by reshadman** [mockery/mockery#407] opened 2014-12-31 10:50 UTC
I mocked the static method `elasticsearchArea` with the following structure:

``` php
$mocked = \Mockery::mock('alias:\Area');

$mocked->shouldReceive('elasticsearchArea')->once()->with($area)->andReturn(
       ['lat' => 53.5658123, 'lng' => 36.54454]);
```

when I only call the `\Area::elasticsearchArea('53.5658123,36.54454')` method once, mockery says that it has been called two times.

**Comment by robertbasic** [comment] 2015-02-11 06:08
I can't reproduce this.

Added this to the Adhoc test and it errors out as expected:

    +    public function testStaticMethodCallCount()
    +    {
    +        \Mockery::setContainer($this->container);
    +        $m = $this->container->mock('alias:MyNamespace\MyClass3');
    +        $m->shouldReceive('mockStatic')->once()->with('a')->andReturn('b');
    +        $c = new MockeryTest_CallsMocks();
    +        $r = $c->callsMock('a');
    +        $r = $c->callsMock('a');
    +        $this->assertSame('b', $r);
    +        $this->container->mockery_verify();
    +        \Mockery::resetContainer();
    +    }
    +}
     
    +class MockeryTest_CallsMocks
    +{
    +    public function callsMock($param)
    +    {
    +        return MyNamespace\MyClass3::mockStatic($param);
    +    }


@bigsinoos Could you please provide the code that calls this `elasticsearchArea` method?

**Comment by padraic** [comment] 2015-02-12 20:06
@bigsinoos Reproducible test case would be appreciated so we can check if needs a fix or has some other logical reason for occurring.

**Comment by robertbasic** [comment] 2015-02-19 15:39
I guess he changed his username?

ping @reshadman

**Comment by reshadman** [comment] 2015-02-19 16:53
@padraic @robertbasic I will provide a test case soon, thank for your notation, really.

**Comment by urosgruber** [comment] 2015-02-27 12:20
I don't know if this is related, but I try to mock

```
$request = \Mockery::mock('alias:Symfony\Component\HttpFoundation\Request');
$request->shouldReceive('setTrustedProxies')->once();
```
and in tearDown cleaned with 

```
\Mockery::close();
```
But then later test failed because it used
```
 $request = Request::create('/', 'GET');
```
Failed with **Fatal error: Call to a member function __call() on a non-object in /Users/uros/Sites/wandera/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(16) : eval()'d code on line 642**

**Comment by robertbasic** [comment] 2017-05-05 10:54
We got no reproducible test case in over 2 years, closing this issue.

**Closed by robertbasic** 2017-05-05 10:54 UTC
Labels: bug
