### ISSUE TITLE
Mock not implementing interface if declared twice with different case

### ISSUE THREAD

**Issue by marcosh** [mockery/mockery#609] opened 2016-06-28 14:14 UTC
I have a test class like the following

```
use Mockery as M;

class MyTest extends \PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        $em = M::mock('Doctrine\ORM\EntityManager');

        var_dump($em instanceof \Doctrine\ORM\EntityManagerInterface); //returns true
    }

    // some tests
}
```

If I add another similar mocking declaration (notice the change in the case), the `var_dump` returns `false`

```
use Mockery as M;

class MyTest extends \PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        $em = M::mock('Doctrine\Orm\EntityManager');
        $em = M::mock('Doctrine\ORM\EntityManager');

        var_dump($em instanceof \Doctrine\ORM\EntityManagerInterface); // returns false
    }

    // some tests
}
```

This happens also if the two mocks are declared in two different classes. I put them together just for simplicity.

I am using version `0.9.4`

**Comment by robertbasic** [comment] 2017-05-06 08:10
Trying with

``` php
<?php

namespace MyNameSpace
{
    interface MyInterface
    {
    }

    class MyClass implements MyInterface
    {
    }
}

namespace
{
    require_once 'vendor/autoload.php';

    $class = Mockery::mock('mynamespace\myclass');
    $class = Mockery::mock('MyNameSpace\MyClass');

    var_dump($class instanceof \MyNameSpace\MyInterface);
}

/*
/home/robert/projects/mockery/adhoc-tests/issue609.php:21:
bool(true)
*/
```

should be a case that does the same thing as your example, but I get the expected `true` as output.

If you could provide a minimum reproducible test case, maybe as an example repository, that includes the smallest amount of dependencies to get the behaviour you're seeing, would be much appreciated!

Also, please provide the operating system you're using.

Thanks!

**Comment by marcosh** [comment] 2017-05-06 14:32
Thanks for getting back to me!

I created this repo with a minimal reproducible test case, as you requested

[https://github.com/marcosh/mockery-bug](https://github.com/marcosh/mockery-bug)

If you comment the first line of the test, it passes.

I tried to investigate a bit the problem, but did not reach a conclusion. I hope to find some time to continue the investigation next week

**Comment by robertbasic** [comment] 2017-05-06 16:08
I see the behaviour reported with the repo that @marcosh provided, digging into it.

**Comment by marcosh** [comment] 2017-05-06 16:11
I investigated a little further, and found out the following.

When trying to mock `Doctrine\Orm\EntityManager` (namespace lowercase), the class `Mockery\Generator\StringManipulation\Pass\ClassPass` will perform a `require` on a temporary file containing a `Doctrine\Orm\EntityManager` class.

Then, when we try to mock `Doctrine\ORM\EntityManaget` (namespace uppercase), inside `Mockery\Generator\DefinedTargetClass::factory`, the call to `new \ReflectionClass($name)` where `$name` is `\Doctrine\ORM\EntityManager` will return

```php
object(ReflectionClass)#31 (1) {
  ["name"]=>
  string(26) "Doctrine\Orm\EntityManager"
}
``` 

(notice the difference in the case of the namespace).

This is actually due to the fact the class names in PHP are case insensitive (see [https://3v4l.org/s0m1A](https://3v4l.org/s0m1A)). Therefore with the first mock a new class is defined and the actual class from `Doctrine` is never loaded

**Comment by robertbasic** [comment] 2017-05-06 16:13
@marcosh but maybe Mockery could somehow make it case-sensitive... I'm a bit rusty with Mockery's internals, this will be a really good exercise to get back in :)

**Comment by robertbasic** [comment] 2017-05-06 18:01
This is due to PHP's case insensitivity with `class_exists` and related functions.

We probably could work around this with lots of hacks, like keeping our own list of declared classes, but I don't think it's worth it.

Development time could be better used on other, more valid and more pressing issues and feature requests.

I vote to close this issue as won't fix.

/cc @davedevelopment @padraic

**Comment by marcosh** [comment] 2017-05-07 15:47
I agree that this issue should probably be closed because the problem does not regard Mockery directly.

It is caused by the fact that `class_exists` is case insesitive, but becomes case sensitive when Composer autoloader is used.

Hopefully this issue will remain as documentation if somebody else stumbles on a similar problem

**Comment by robertbasic** [comment] 2017-05-07 15:55
I have added a note about this to my documentation ticket.

Closing this issue as @marcosh agrees.

**Closed by robertbasic** 2017-05-07 15:55 UTC
Labels: bug, investigate
