### ISSUE TITLE
namedMock() not working with constant attributes.

### ISSUE THREAD

**Issue by sameernyaupane** [mockery/mockery#622] opened 2016-09-20 10:06 UTC
```
class ClassConstantStub
{
    const CHUNK_SIZE = 4194304;
}
```

```
public function test_execute_WhenArchiveIsLessThan4MB_ReturnArrayWithRequiredData() {
$dropbox  = Mockery::namedMock('DropboxClient', 'ClassConstantStub');

var_dump(DropboxClient::CHUNK_SIZE);
```

The ClassConstantStub isn't taken into account with namedMock(), and there is no error at all either.

I'm getting the fatal error when the execution reaches var_dump.

`Fatal error: Undefined class constant`

Am I doing something wrong here?

Thanks

**Comment by davedevelopment** [comment] 2016-09-20 11:51
Possibly an import/namespace issue? Everything in the same file/namespace works well:

```
<?php

require "vendor/autoload.php";

class ClassConstantStub
{
    const CHUNK_SIZE = 4194304;
}

$dropbox  = Mockery::namedMock('DropboxClient', 'ClassConstantStub');
                                                                     
var_dump(DropboxClient::CHUNK_SIZE); // int(4194304)
```

**Comment by sameernyaupane** [comment] 2016-09-20 12:49
Weird, still same issue:

```
<?php
require_once dirname(dirname(dirname(dirname(dirname(__FILE__)))))
	. DIRECTORY_SEPARATOR . 'lib'
	. DIRECTORY_SEPARATOR . 'model'
	. DIRECTORY_SEPARATOR . 'export'
	. DIRECTORY_SEPARATOR . 'class-ai1wmde-export-upload.php';

class ClassConstantStub
{
    const CHUNK_SIZE = 4194304;
}

class Ai1wmde_Export_UploadTest extends Ai1wm_Unit_Test
{
	private function mock($class)
	{
		return Mockery::mock($class);  
	}

	private function mockWithStub($class, $stub)
	{
		return Mockery::namedMock($class, $stub);  
	}

	public function tearDown()
	{
		Mockery::close();
	}
	
	public function test_execute_WhenArchiveIsLessThan4MB_ReturnArrayWithRequiredData()
	{
		$dropbox  = $this->mockWithStub('ServMaskDropboxClient', 'ClassConstantStub');

		var_dump(ServMaskDropboxClient::CHUNK_SIZE);
```

Even renaming 'ClassConstantStub' to a non existing name gives no error.

**Comment by robertbasic** [comment] 2017-05-06 07:54
@sameernyaupane doing what you did, still provides the expected output.

``` php
<?php

require_once 'vendor/autoload.php';

class ClassConstantStub
{
    const CHUNK_SIZE = 4194304;
}

class Export_UploadTest
{
    private function mock($class)
    {
        return Mockery::mock($class);
    }

    private function mockWithStub($class, $stub)
    {
        return Mockery::namedMock($class, $stub);
    }

    public function tearDown()
    {
        Mockery::close();
    }

    public function test_execute_WhenArchiveIsLessThan4MB_ReturnArrayWithRequiredData()
    {
        $dropbox  = $this->mockWithStub('DropboxClient', 'ClassConstantStub');
        var_dump(DropboxClient::CHUNK_SIZE);
    }
}

$test = new Export_UploadTest();
$test->test_execute_WhenArchiveIsLessThan4MB_ReturnArrayWithRequiredData();

/*
/home/robert/projects/mockery/adhoc-tests/issue622.php:30:
int(4194304)
*/
```

I have tried every tagged release since 0.9.0, including 1.0.0-alpha1, as well as current master.

I don't know what the `Unit_Test` which you're extending does, but this doesn't seem like a bug in Mockery since we can't reproduce it.

I'm going to close this issue as we can't reproduce it.

If this is still an issue for you, please reopen it, but do provide a small, reproducible test case that proves the issue you are seeing.

Thank you!

**Closed by robertbasic** 2017-05-06 07:54 UTC
Labels: bug, investigate

**Comment by agxmeister** [comment] 2017-12-15 11:38
Looks like such issue occurs if ClassConstantStub could not be loaded by autoloader. I am faced with the same behavior and just fix it by moving ClassConstantStub into a separate file.

Mockery is grate, but there is one bad thing: if it unable to create appropriate mock, it does not report anything. I realy hope it will be fixed in future releases. :-)
