### ISSUE TITLE
Hamcrest conflicts with PHPUnit

### ISSUE THREAD

**Issue by Ocramius** [mockery/mockery#464] opened 2015-04-07 15:02 UTC
As it stands, hamcrest-php conflicts with PHPUnit:
- [`any` defined by hamcrest](https://github.com/hamcrest/hamcrest-php/blob/18ec485a0696da23a0d5d2b21b1961d77e42d27d/hamcrest/Hamcrest.php#L362)
- [`any` defined by phpunit](https://github.com/sebastianbergmann/phpunit/blob/8044ba2d89cb7c9c5ba969403e53191eb7eb9aca/src/Framework/Assert/Functions.php#L18)

Both nicely _NOT_ namespaced

_insert long sigh here_

**Comment by aik099** [comment] 2015-04-07 15:04
I wonder how Mockery unit tests pass knowing that they use Hamcrest and PHPUnit together.

**Comment by GrahamCampbell** [comment] 2015-04-07 15:19
Not a conflict: https://github.com/sebastianbergmann/phpunit/blob/8044ba2d89cb7c9c5ba969403e53191eb7eb9aca/src/Framework/Assert/Functions.php#L18

**Comment by GrahamCampbell** [comment] 2015-04-07 15:20
hamcrest defines them only if phpunit has't defined that function

**Comment by aik099** [comment] 2015-04-07 15:28
But if libraries are included in different order: first Hamcrest and then PHPUnit, then all fails.

**Comment by Ocramius** [comment] 2015-04-07 15:28
Depending on autoloader priority, there may or may not be a crash. I had a crash this morning, heh...

**Comment by aik099** [comment] 2015-04-07 15:36
If Hamcrest conflicts with PHPUnit, then shouldn't this be reported to Hamcrest repo? And initially we (at Hamcrest) stopped including global function definitions, like `any` and such in Composer (because we have namespaced class for that), but people started complaining that their usages of these functions no longer work. Then we added it to Composer auto-loader and that caused the problem.

**Comment by GrahamCampbell** [comment] 2015-04-07 15:41
phpunit fixed this in 4.6.2 i think?

**Comment by Ocramius** [comment] 2015-04-07 15:42
I mainly reported it here because the dependency was introduced in the latest minor version, as far as I know.

It can indeed be reported on Hamcrest and/or PHPUnit as well.

Possibly related: sebastianbergmann/phpunit#1625

**Comment by aik099** [comment] 2015-04-07 15:44
https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/Assert/Functions.php - not fixed. Same in 4.6 and 4.7 branches of PHPUnit.

**Comment by padraic** [comment] 2015-04-07 15:55
I asked @Ocramius to report here so we could keep an eye on how this develops ;). We rely on Hamcrest, so if requiring it brings out this issue, all the better to see it resolved I hope.

All round, it's hard to fix since it's probably a violation of semver to toggle functions on/off too much. What we need eventually is a migration to namespacing in major versions. @Ocramius Might be worth reporting to PHPUnit also as something for 5.0 if nothing else.

In the meantime...suggestions?

**Comment by davedevelopment** [comment] 2015-04-07 17:27
requiring 5.6 is a big leap, I think a toggle is all we have. Unconditionally dumping in the global space isn't very nice, phpunit should probably make changes and I think checks around every function is a better approach. I also think an ENV var to skip all, but I imagine that's a bit dirty for some.

``` php
if (getenv('MOCKERY_SKIP_GLOBALS')) {
    return;
}

if (!function_exists('assertThat')) {
    function assertThat(...
}
```

Yes it could leave to a mix of names in the global space, but better than nothing.

**Comment by padraic** [comment] 2015-04-10 21:28
So effectively we've crossed all the streams. Mockery now pulls in Hamcrest, and PHPUnit recently had a change (https://github.com/sebastianbergmann/phpunit/pull/1625) where its functions are autoloaded via composer.json. So it's a race to see whose functions get defined, and the wrong order will break Mockery.

The change creating problems is restricted to PHPUnit's master branch (the upcoming alpha version). It's not an issue as far as I can tell for any currently stable or beta version.

Conflicting dependencies is still our problem, so I'll label as a tentative bug. I've reported it for PHPUnit though whether that prompts a change is unknown. I'm sure Sebastian will let us know in due course and we can take further action from there.

**Comment by Giuseppe-Mazzapica** [comment] 2015-04-20 20:48
As of now, even using stable releases for both PHPUnit and Mockery makes tests not runnable for this issue.

The only way I found to fix it was require the exact Mockery version `0.9.3`.

I really don't want be rude or something like that, I just love this package, but please, next time don't use patch version to push a new dependency.

People expects that using a require like: `"mockery/mockery": "^0.9.1"` updates should not break anything.

And, for me, you should at least consider to release a 0.9.5 that remove again that dependency. Even because in 0.9.4 there is [no a single line of PHP that have been changed](https://github.com/padraic/mockery/compare/0.9.4...master).

**Comment by davedevelopment** [comment] 2015-04-20 21:16
@Giuseppe-Mazzapica I believe PHPUnit were reverting their change, so this shouldn't be a problem now?

**Comment by Giuseppe-Mazzapica** [comment] 2015-04-20 21:26
@davedevelopment Yes, PHPUnit removed files from "files" autoload.

The problem is that *before* PHPUnit made that change (it was pretty recently), to use asserting functions one had to *manually* `require` file containing asserting functions.

If you ever did that, now you have 2 chances:
 1. remove the manual `require"` that means also remove all the functions calls from all tests and don't use use them anymore
 2. require Mockery 0.9.3

**Comment by davedevelopment** [comment] 2015-04-20 21:54
@Giuseppe-Mazzapica oh I see, you're already using those PHPUnit functions. 

Well I'm happy to drop the requirement for now, but I'd prefer things be improved upstream. Tighter checks in hamcrest as I mentioned above would allow you to include both files in the desired order.

**Comment by Giuseppe-Mazzapica** [comment] 2015-04-20 22:04
@davedevelopment Yes, I use PHPUnit functions since years, and Mockery since more or less it exists. 

They always worked together with no issue till today. I commented here because that meaningful change was introduced in a PATCH version, that is totally a bad idea.

**Comment by davedevelopment** [comment] 2015-04-20 22:06
@Giuseppe-Mazzapica I understand the annoyance, I've also had to freeze the mockery version I use. We do try and keep a certain level of BC, but as per semver, until we go 1.0, mockery shouldn't be considered stable.

**Comment by padraic** [comment] 2015-04-20 22:59
If it's still causing issues, then we can revert the change. Upstream need to reach some sort of compromise on global functions...

@Giuseppe-Mazzapica I appreciate adding it caused problems, but we do follow semver and Mockery has no major version at this version. It technically remains an ongoing development work. There's small comfort there, I understand.

@davedevelopment If we both agree, it should likely be done sooner rather than later. Thoughts?

**Comment by Giuseppe-Mazzapica** [comment] 2015-04-20 23:44
@padraic I'm watching :)

**Comment by aik099** [comment] 2015-04-21 07:00
So people can't use short function names of both Hamcrest and PHPUnit matchers at same time, which is bad.

Maybe there is some way for user to explicitly specify which library matchers wins regardless of include order?

**Comment by Ocramius** [comment] 2015-04-21 07:52
Note that this unfortunate series of events is mainly my fault

 - we are using PHPUnit's assertion functions (not namespaced) in some
horrible codebase at work
 - I fixed this via sebastianbergmann/phpunit#1625
 - The fix worked for me until hamcrest was introduced as a dependency here
 - I put a `"conflicts": {"hamcrest/hamcrest-php": "*"}` in my
`composer.json` and mockery downgraded (that's how I found out about the
new dep)

Chicken-egg, but I think PHPUnit is a bigger fish here :-\

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by padraic** [comment] 2015-04-21 10:34
@Ocramius It's your fault? :bomb: ;)

**Comment by davedevelopment** [comment] 2015-04-21 18:56
I'm with Marco that PHPUnit is the bigger fish. Given that they've rolled back anyway, I propose that hamcrest merge hamcrest/hamcrest-php#25, giving people the option to manually load PHPUnit's file first. There could be a weird mix of functions (i.e. only some of hamcrest's), but that's what you get if you play with fire/global functions.

**Comment by BallisticPain** [comment] 2015-04-27 14:51
I wish this were cleaner... I have just recently started using Mockery and then started reading about Hamcrest. I was excited to use Hamcrest to make my tests more readable. Then figured out there were namespacing issues (and a lack thereof). Right now I'm using a h::assertThat() but would much prefer to have the ability for it to be clean. Has anyone attempted to contact phpUnit developers and have them introduce using Hamcrest instead of developing their own "plain english" version?

**Comment by aik099** [comment] 2015-04-27 16:30
So it's `h::assertThat(hm::any())` vs `assertThat(any())`. Looks the same to me.

**Comment by padraic** [comment] 2015-05-11 14:25
Anyone we need to ping on the Hamcrest side to progress this? If we're facing a long wait, I'd prefer to revert the require for the time being and push out a patch release if there needs to be one for PHP 5.3.

**Comment by davedevelopment** [comment] 2015-05-11 14:42
I just merged hamcrest/hamcrest-php#25 which should make things a little better

**Comment by padraic** [comment] 2015-05-11 18:55
Grand, do we need a Hamcrest release before we run ahead and do something in a release of our own? We'll probably need to forgo dropping PHP 5.3 for one more patch level so we don't leave anyone there stranded with this issue.

**Comment by davedevelopment** [comment] 2015-05-11 19:19
@padraic I just tagged it https://github.com/hamcrest/hamcrest-php/releases/tag/v1.2.2

Given PHPUnit rolled back, we don't *need* to tag a bugfix release, as we can suggest people upgrade 1.2.2 of hamcrest and whatever version it is of PHPUnit? 

No harm in adding one though, we've already bumped the composer.json in master so we'd need a branch of the 0.9.4 tag to put something out.

**Comment by davedevelopment** [comment] 2016-01-08 11:37
I'm at a point where I'm ready to back the hamcrest dependency out. I use the php assert functions in some of my test suites, and I aren't able to use mockery 1.0.x because of it.

**Comment by davedevelopment** [comment] 2016-01-08 11:38
The forced ordering of the includes I mentioned earlier in this thread doesn't work if you're calling `vendor/bin/phpunit`, as it calls `vendor/autoload.php` directly, before getting chance in a bootstrap script etc.

**Comment by BallisticPain** [comment] 2016-01-12 20:39
I like the Hamcrest concept, but in practice we stopped using it and backed
it out of where we started to.

Jarvis Stubblefield
IT & Business Consultant
Mobile: 615-974-6618

**Comment by aik099** [comment] 2016-01-13 08:26
I like Hamcrest, but not global functions it provides. Better to use namespaced matcher versions.

**Comment by Giuseppe-Mazzapica** [comment] 2016-01-19 09:43
I still have issue with this, with latest version on anything. I'm forced to require Mockery exact version 0.9.3. This is super annoying, expecially considering that Hamcrest is not a real dependency and Mockery works just fine without it.

**Comment by davedevelopment** [comment] 2016-01-19 09:44
@padraic what do you think? I can't see phpunit or hamcrest moving to namespaced functions any time soon...

**Comment by aik099** [comment] 2016-01-19 10:29
Hamcrest have both namespaced and non-namespaced versions. I think that Hamcrest should avoid using non-namespaced functions by default in `composer.json`.

Then at least developer have some control to ensure that PHPUnit's own functions are included first if he/she likes Hamcrest global functions a lot.

**Comment by davedevelopment** [comment] 2016-01-19 11:30
@aik099 sorry my bad, I did know hamcrest had them, slipped my mind. 

I just created hamcrest/hamcrest-php#35 to open a discussion on this there

**Comment by aik099** [comment] 2016-01-19 11:48
OK.

**Comment by robertbasic** [comment] 2017-05-12 04:31
@davedevelopment @aik099 @padraic if I'm reading this whole thing right, ever since Hamcrest 2, and us requiring it, this should no longer be an issue?

**Closed** 2017-05-12 07:25 UTC
Labels: bug, investigate
