### ISSUE TITLE
Error: Class 'Mockery' not found

### ISSUE THREAD

**Issue by blink2004** [mockery/mockery#966] opened 2019-04-03 17:18 UTC
Try use Mocker in PHPUnit:
```
use \Mockery as m;

class adminTest extends TestCase {

    function testGetAdmin(){
        $mock = m::mock(__NAMESPACE__, "foo")->andReturn(3);

        $this->assertEquals(3, foo());

        m::close();
    }

} 
```
but output after execute `phpunit -v`:
`Error: Class 'Mockery' not found`

**Comment by GrahamCampbell** [comment] 2019-04-03 23:15
Have you let phpunit know about the autoloader in the config?

**Comment by blink2004** [comment] 2019-04-04 14:02
`phpunit.xml` in `./` directory:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/8.0/phpunit.xsd"
	     colors="true"
         bootstrap="vendor/autoload.php"
         executionOrder="depends,defects"
         forceCoversAnnotation="true"
         verbose="true">
    <testsuites>
        <testsuite name="default">
            <directory suffix="Test.php">tests</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
        ...
        </whitelist>
    </filter>
</phpunit>

```
`composer.json`:
```json
{
    "require-dev": {
        "phpunit/phpunit": "^8.0",
        "mockery/mockery": "^1.2"
    }
}
```

**Comment by GrahamCampbell** [comment] 2019-04-04 21:40
What happens when you run `composer info` please. Could you put the output on gist, and link to it here? Also, what happens when you run `composer exec phpunit -v`?

**Comment by GrahamCampbell** [comment] 2019-04-04 21:42
I would expect to see:

```
$ composer info | grep mockery
mockery/mockery                    1.2.2    Mockery is a simple yet flexible PHP mock object framework
```

If nothing shows, then you need to run `composer update`.

**Comment by blink2004** [comment] 2019-04-05 22:01
`$ php composer.phar info` get result https://justpaste.it/7nibz.
`$ php composer.phar info | grep mockery`:
```bash
mockery/mockery                    1.2.2   Mockery is a simple yet flexible PHP mock object f...
```

**Comment by blink2004** [comment] 2019-04-09 10:50
Did you reproduce it?

**Comment by davedevelopment** [comment] 2019-04-09 11:04
I can't reproduce using this:

# phpunit.xml
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/8.0/phpunit.xsd"
             colors="true"
         bootstrap="vendor/autoload.php"
         executionOrder="depends,defects"
         forceCoversAnnotation="true"
         verbose="true">
    <testsuites>
        <testsuite name="default">
            <directory suffix="Test.php">tests</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
        </whitelist>
    </filter>
</phpunit>
```

# composer.json
``` json
{
    "require-dev": {
        "phpunit/phpunit": "^8.0",
        "mockery/mockery": "^1.2"
    }
}
```

# tests/adminTest.php

Note the changes, I don't think the test you supplied would ever work properly.

``` php
<?php

use \Mockery as m;
use PHPUnit\Framework\TestCase;

class adminTest extends TestCase {

    function testGetAdmin(){
        $mock = m::mock();
        $mock->allows()->foo()->andReturn(3);

        $this->assertEquals(3, $mock->foo());

        m::close();
    }

}
```

# Output
```
davem@wes:temp$ vendor/bin/phpunit -v
PHPUnit 8.1.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.16 with PCOV 1.0.1-dev
Configuration: /home/davem/src/temp/phpunit.xml

.                                                                   1 / 1 (100%)

Time: 15 ms, Memory: 2.00 MB

OK (1 test, 1 assertion)
davem@wes:temp$
```

**Comment by blink2004** [comment] 2019-04-11 10:26
I just created from scratch simple project with PHPUnit and Mockery only. Repeat code above and it work perfectly.

But when I'm using this code in real project (CMS WordPress), I'm mocking method `_get_admin_bar_pref()`, which before and after mock show result `1`.

Code:
```php
    function testMockFunction(){
        print_r(_get_admin_bar_pref()); // 1

        $mock = m::mock();
        $mock->allows()->_get_admin_bar_pref()->andReturn(4);

        print_r(_get_admin_bar_pref()); // 1
        $this->assertEquals(3, _get_admin_bar_pref()); // don't throw exception!

        m::close();
    }
```

What is wrong?

**Comment by davedevelopment** [comment] 2019-05-13 15:53
@blink2004 Mockery doesn't mock global functions like that. When you call

``` php
        $mock->allows()->_get_admin_bar_pref()->andReturn(4);
```

You are telling mockery that you are allowing people to call the instance method `_get_admin_bar_pref` on the `$mock` object, rather than the global `_get_admin_bar_pref` function. 

You can mock global functions if they're called from within a namespace, but knowing wordpress, you won't be that lucky and you won't be able to mock that function at all.

**Comment by robertbasic** [comment] 2019-10-24 06:50
Closing due to trying to mock global functions with Mockery, something that Mockery wasn't meant to be used for.

Thanks @blink2004!

**Closed by robertbasic** 2019-10-24 06:50 UTC
