### ISSUE TITLE
Final method mocking does not work throgh proxy

### ISSUE THREAD

**Issue by tflori** [mockery/mockery#660] opened 2016-12-27 15:56 UTC
After some debugging I found out the method is final but in the docs it says I can mock a final method with proxied partial mock. But it keeps annoying me with "should be called exactly 1 times but called 0 times" :cry: 

Example:
```php
<?php

require_once 'vendor/autoload.php';

class TestClass
{
        final public function testMethod($v)
        {
                return $v === 'foobar';
        }
}

$mock = Mockery::mock(new TestClass());
$mock->shouldReceive('testMethod')->with('foobar')->once();

$mock->testMethod('foobar');

Mockery::close();
```

**Comment by bitwombat** [comment] 2017-02-08 10:23
> But it keeps annoying me with "should be called exactly 1 times but called 0 times"

Isn't that ->once() doing its job?

**Comment by robertbasic** [comment] 2017-02-12 18:37
Hm, this works if you mark the class final as well.

According to this test, final methods from non-final classes are removed: https://github.com/padraic/mockery/blob/63987b7de6ca423c27803e1f4a52bcfaa211667e/tests/Mockery/Generator/MockConfigurationTest.php#L90-L97

**Comment by robertbasic** [comment] 2017-02-12 18:44
And looks like this test is bad https://github.com/padraic/mockery/blob/master/tests/Mockery/ContainerTest.php#L297-L304

It has an expectation that the mocked `foo` method will return `'bar'`, but it actually returns the `'bar'` from the actual method https://github.com/padraic/mockery/blob/master/tests/Mockery/ContainerTest.php#L1456-L1459

**Comment by robertbasic** [comment] 2017-02-12 18:47
And this test gets it correctly: https://github.com/padraic/mockery/blob/63987b7de6ca423c27803e1f4a52bcfaa211667e/tests/Mockery/ContainerTest.php#L315-L321

**Comment by robertbasic** [comment] 2017-05-05 04:42
Possibly related #605

**Comment by robertbasic** [comment] 2018-02-04 08:33
After investigating #605 a bit more in detail, this is by design. Any and all tests I mentioned before are indeed correct.

The documentation needs updating saying that final methods can't be mocked/proxied/whatever, and that the actual final method will be used always.

**Comment by robertbasic** [comment] 2018-02-04 19:40
There's #843 now that hopefully makes the documentation more clear for this.

**Comment by robertbasic** [comment] 2018-02-05 11:03
#843 got merged, so closing this now.

**Closed by robertbasic** 2018-02-05 11:03 UTC
Labels: documentation, won't fix
